name: Run Cypress test suite
on: [workflow_dispatch]
jobs:
    e2e:
        name: Cypress Test
        runs-on: ubuntu-latest
        strategy:
            matrix:
                wp-version: ['"WordPress/WordPress#master"']
        steps:
            - name: Clone repo
              uses: actions/checkout@v3
            - name: Install dependencies
              run: |
                  composer install
                  npm ci --ignore-engines --force
                  npm run build

            - name: Maybe remove .wp-env.json
              if: ${{ matrix.wp-version }}
              run: rm .wp-env.json

            - name: Maybe change WP version
              uses: jsdaniell/create-json@v1.2.1
              if: ${{ matrix.wp-version }}
              with:
                  name: '.wp-env.json'
                  json: '{
                    "core": ${{ matrix.wp-version }},
                    "plugins":["."]
                  }'

            - name: Start server
              run: |
                  npm install -g @wordpress/env
                  wp-env start --update
                  
            - name: Cypress run
              uses: cypress-io/github-action@v4
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            - uses: actions/upload-artifact@v3
              if: failure()
              with:
                  name: cypress-screenshots
                  path: cypress/screenshots
            - uses: actions/upload-artifact@v3
              if: failure()
              with:
                  name: cypress-videos
                  path: cypress/videos
